### ISSUE TITLE
Project :: Help

### ISSUE THREAD

**Issue by ghost** [OxyProgrammer/XPence#1]
Hi,

Was wondering you can assist me with something relating this project?

**Comment by OxyProgrammer** [comment]
Can you please be a little more specific?

**Comment by ghost** [comment]
@OxyProgrammer My apologizes so basically Im in the process of making a Inventory system that uses a similar structure to XPence but Im rather stuck where you use navigation was wondering can you assist me with my project. 

May I add you to my project so you can see what im referring to?

**Comment by OxyProgrammer** [comment]
Apologies for late reply.
Please do.

Thanks,
Sid

Get Outlook for iOShttps://aka.ms/o0ukef

On Fri, Jul 22, 2016 at 1:46 AM +0530, "di48l069" <notifications@github.com<mailto:notifications@github.com>> wrote:

@OxyProgrammerhttps://github.com/OxyProgrammer My apologizes so basically Im in the process of making a Inventory system that uses a similar structure to XPence but Im rather stuck where you use navigation was wondering can you assist me with my project.

May I add you to my project so you can see what im referring to?

##

**Comment by ghost** [comment]
@OxyProgrammer My apologies on late response can you please mail @ di48l069@gmail.com so I can discuss with you what I need help with thank you.
